feat: Add support for building and installing sqlcipher3 with OpenSSL on macOS
dylanljones/pyrekordbox pull request #134
Opened 2024-05-27 10:14 UTC by Bide-UK

- Added function to set SQLCipher paths, including OpenSSL paths, to ensure headers and libraries are correctly located.
- Updated environment variables.
- Modified the `install_pysqlcipher` function to use `pypa/build` and `pypa/installer` for building and installing sqlcipher3.
- Implemented checks for existing symlinks before creating them to avoid FileExistsError.
- Ensured compatibility with both Intel and M1 Mac architectures by adjusting symlink creation logic.

2025-02-02 17:46 UTC, dylanljones commented
Hey @Bide-UK , sorry for the super late response. 

Awesome work, really wanted to add Mac supported for this. Did you check if the install process is still compatible with Windows?
Otherwise, we can merge:)

If you can't test on Windows give me a little time and i will make sure it works!

2025-02-10 16:20 UTC, dylanljones commented
Man, thank you so much for sharing @cvdub! I tested it on Windows, and it works perfectly!! I've been looking for wheels for ages, even tried making my own GitHub actions to build them but never managed to do so successfully... 
This will make the installation process so much easier. Will add it to the next version ASAP!

@Bide-UK, will still check out your PR, would be a nice fallback option:)

2025-02-10 16:31 UTC, dylanljones requested changes
This looks pretty nice, although i think in the current state this will break the Windows install (see comment). A simple platform check should resolve this, as most of the install process on Windows is unaffected by your PR!

2025-02-10 16:31 UTC, dylanljones commented on pyrekordbox/__main__.py
> +    # Set environment paths and create symlinks
Should this be done on all platforms? It seems like at least the `create_symlinks` method won't work on Windows. Maybe we can just add a platform check before calling it?

2025-02-15 20:36 UTC, Tower450 commented
i am trying to open the master.db with sqlcypher and it fails. Any more details on that?

```
python -m pyrekordbox download-key
sqlcipher master.db
```

2025-08-07 14:17 UTC, dylanljones commented
Closing as i think this is not needed anymore since we are using the pre-built wheels:)

2025-08-07 14:17 UTC, closed without merging